import Database from 'better-sqlite3';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { Collection, CollectionType, Field, SavedMapping } from '../../shared/types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Data directory is configurable via env so hosts with a persistent disk can
// point it somewhere durable. Defaults to server/data/terrain.db.
//
// IMPORTANT: this must resolve to server/data, never anything inside dist/ —
// dist/ gets regenerated by `npm run build`, which runs on every deploy, so
// a database placed inside it would be silently wiped on every redeploy.
// The compiled output nests as dist/server/src/db.js (tsc's rootDir spans
// both server/ and shared/), which sits one level deeper than the
// uncompiled server/src/db.ts does in dev — detect which case we're in
// rather than hardcoding one depth.
const isCompiled = __dirname.split(path.sep).includes('dist');
const dataDir =
  process.env.DATA_DIR ||
  (isCompiled ? path.join(__dirname, '..', '..', '..', 'data') : path.join(__dirname, '..', 'data'));
fs.mkdirSync(dataDir, { recursive: true });
const dbPath = path.join(dataDir, 'terrain.db');

export const db = new Database(dbPath);
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS collections (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    file_name TEXT NOT NULL,
    fields TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )
`);

// Migration: earlier deployments' databases won't have created_by yet.
// SQLite has no "ADD COLUMN IF NOT EXISTS", so add it and ignore the error
// if it's already there (existing rows get '' for createdBy).
try {
  db.exec(`ALTER TABLE collections ADD COLUMN created_by TEXT NOT NULL DEFAULT ''`);
} catch {
  /* column already exists — nothing to do */
}

db.exec(`
  CREATE TABLE IF NOT EXISTS mappings (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    source_name TEXT NOT NULL,
    target_name TEXT NOT NULL,
    rows TEXT NOT NULL,
    saved_by TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )
`);

interface CollectionRow {
  id: string;
  name: string;
  type: string;
  file_name: string;
  fields: string;
  created_by: string;
  created_at: number;
}

function rowToCollection(row: CollectionRow): Collection {
  return {
    id: row.id,
    name: row.name,
    type: row.type as CollectionType,
    fileName: row.file_name,
    fields: JSON.parse(row.fields) as Field[],
    createdBy: row.created_by || '',
    createdAt: row.created_at,
  };
}

export function listCollections(): Collection[] {
  const rows = db
    .prepare('SELECT * FROM collections ORDER BY created_at DESC')
    .all() as CollectionRow[];
  return rows.map(rowToCollection);
}

export function getCollection(id: string): Collection | undefined {
  const row = db.prepare('SELECT * FROM collections WHERE id = ?').get(id) as
    | CollectionRow
    | undefined;
  return row ? rowToCollection(row) : undefined;
}

// Case-insensitive name lookup, used to enforce unique collection names.
// Pass excludeId when renaming so a collection doesn't collide with itself.
export function findCollectionByName(name: string, excludeId?: string): Collection | undefined {
  const row = excludeId
    ? (db
        .prepare('SELECT * FROM collections WHERE LOWER(name) = LOWER(?) AND id != ?')
        .get(name, excludeId) as CollectionRow | undefined)
    : (db.prepare('SELECT * FROM collections WHERE LOWER(name) = LOWER(?)').get(name) as
        | CollectionRow
        | undefined);
  return row ? rowToCollection(row) : undefined;
}

export function renameCollection(id: string, name: string): Collection | undefined {
  db.prepare('UPDATE collections SET name = ? WHERE id = ?').run(name, id);
  return getCollection(id);
}

export function insertCollection(c: Collection): void {
  db.prepare(
    `INSERT INTO collections (id, name, type, file_name, fields, created_by, created_at)
     VALUES (@id, @name, @type, @fileName, @fields, @createdBy, @createdAt)`
  ).run({
    id: c.id,
    name: c.name,
    type: c.type,
    fileName: c.fileName,
    fields: JSON.stringify(c.fields),
    createdBy: c.createdBy,
    createdAt: c.createdAt,
  });
}

export function deleteCollection(id: string): boolean {
  const result = db.prepare('DELETE FROM collections WHERE id = ?').run(id);
  return result.changes > 0;
}

/* ============================= SAVED MAPPINGS ============================= */

interface MappingRowRecord {
  id: string;
  source_id: string;
  target_id: string;
  source_name: string;
  target_name: string;
  rows: string;
  saved_by: string;
  created_at: number;
}

function rowToSavedMapping(row: MappingRowRecord): SavedMapping {
  return {
    id: row.id,
    sourceId: row.source_id,
    targetId: row.target_id,
    sourceName: row.source_name,
    targetName: row.target_name,
    rows: JSON.parse(row.rows),
    savedBy: row.saved_by,
    createdAt: row.created_at,
  };
}

export function listSavedMappings(): SavedMapping[] {
  const rows = db
    .prepare('SELECT * FROM mappings ORDER BY created_at DESC')
    .all() as MappingRowRecord[];
  return rows.map(rowToSavedMapping);
}

export function getSavedMapping(id: string): SavedMapping | undefined {
  const row = db.prepare('SELECT * FROM mappings WHERE id = ?').get(id) as
    | MappingRowRecord
    | undefined;
  return row ? rowToSavedMapping(row) : undefined;
}

export function insertSavedMapping(m: SavedMapping): void {
  db.prepare(
    `INSERT INTO mappings (id, source_id, target_id, source_name, target_name, rows, saved_by, created_at)
     VALUES (@id, @sourceId, @targetId, @sourceName, @targetName, @rows, @savedBy, @createdAt)`
  ).run({
    id: m.id,
    sourceId: m.sourceId,
    targetId: m.targetId,
    sourceName: m.sourceName,
    targetName: m.targetName,
    rows: JSON.stringify(m.rows),
    savedBy: m.savedBy,
    createdAt: m.createdAt,
  });
}

export function deleteSavedMapping(id: string): boolean {
  const result = db.prepare('DELETE FROM mappings WHERE id = ?').run(id);
  return result.changes > 0;
}
