import Database from 'better-sqlite3';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { Collection, CollectionType, CollectionSource, InternalOrExternalType, CollectionStatus, Field, SavedMapping, Category, SourceSystem } from '../../shared/types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Data directory is configurable via env so hosts with a persistent disk can
// point it somewhere durable. Defaults to server/data/terrain.db.
//
// IMPORTANT: this must resolve to server/data, never anything inside dist/ —
// dist/ gets regenerated by `npm run build`, which runs on every deploy, so
// a database placed inside it would be silently wiped on every redeploy.
// The compiled output nests as dist/server/src/db.js (tsc's rootDir spans
// both server/ and shared/), which sits one level deeper than the
// uncompiled server/src/db.ts does in dev — detect which case we're in
// rather than hardcoding one depth.
const isCompiled = __dirname.split(path.sep).includes('dist');
const dataDir =
  process.env.DATA_DIR ||
  (isCompiled ? path.join(__dirname, '..', '..', '..', 'data') : path.join(__dirname, '..', 'data'));
fs.mkdirSync(dataDir, { recursive: true });
const dbPath = path.join(dataDir, 'terrain.db');

export const db = new Database(dbPath);
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS collections (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    file_name TEXT NOT NULL,
    fields TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )
`);

// Migration: earlier deployments' databases won't have created_by yet.
// SQLite has no "ADD COLUMN IF NOT EXISTS", so add it and ignore the error
// if it's already there (existing rows get '' for createdBy).
try {
  db.exec(`ALTER TABLE collections ADD COLUMN created_by TEXT NOT NULL DEFAULT ''`);
} catch {
  /* column already exists — nothing to do */
}
try {
  db.exec(`ALTER TABLE collections ADD COLUMN source TEXT NOT NULL DEFAULT ''`);
} catch {
  /* column already exists — nothing to do */
}
try {
  db.exec(`ALTER TABLE collections ADD COLUMN client_type TEXT NOT NULL DEFAULT ''`);
} catch {
  /* column already exists — nothing to do */
}
try {
  db.exec(`ALTER TABLE collections ADD COLUMN status TEXT NOT NULL DEFAULT ''`);
} catch {
  /* column already exists — nothing to do */
}
try {
  db.exec(`ALTER TABLE collections ADD COLUMN edited_by TEXT NOT NULL DEFAULT ''`);
} catch {
  /* column already exists — nothing to do */
}
try {
  db.exec(`ALTER TABLE collections ADD COLUMN edited_at INTEGER`);
} catch {
  /* column already exists — nothing to do */
}

db.exec(`
  CREATE TABLE IF NOT EXISTS mappings (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    source_name TEXT NOT NULL,
    target_name TEXT NOT NULL,
    rows TEXT NOT NULL,
    saved_by TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )
`);

// Categories are user-managed, persisted data (not a hardcoded list) — this
// is what powers "Add New Category" in the New Collection form. Name is
// case-insensitively unique at the DB level as a safety net, in addition to
// the explicit application-level duplicate check in the route handler.
db.exec(`
  CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE COLLATE NOCASE,
    created_by TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL
  )
`);

// Source System — same pattern as categories: user-managed, persisted,
// case-insensitively unique, powers "Add New Source System" in the form.
db.exec(`
  CREATE TABLE IF NOT EXISTS source_systems (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE COLLATE NOCASE,
    created_by TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL
  )
`);

interface CollectionRow {
  id: string;
  name: string;
  type: string;
  source: string;
  client_type: string;
  status: string;
  file_name: string;
  fields: string;
  created_by: string;
  created_at: number;
  edited_by: string;
  edited_at: number | null;
}

function rowToCollection(row: CollectionRow): Collection {
  return {
    id: row.id,
    name: row.name,
    type: row.type as CollectionType,
    source: (row.source || '') as CollectionSource,
    clientType: (row.client_type || '') as InternalOrExternalType,
    status: (row.status || '') as CollectionStatus,
    fileName: row.file_name,
    fields: JSON.parse(row.fields) as Field[],
    createdBy: row.created_by || '',
    createdAt: row.created_at,
    editedBy: row.edited_by || '',
    editedAt: row.edited_at ?? null,
  };
}

export function listCollections(): Collection[] {
  const rows = db
    .prepare('SELECT * FROM collections ORDER BY created_at DESC')
    .all() as CollectionRow[];
  return rows.map(rowToCollection);
}

export function getCollection(id: string): Collection | undefined {
  const row = db.prepare('SELECT * FROM collections WHERE id = ?').get(id) as
    | CollectionRow
    | undefined;
  return row ? rowToCollection(row) : undefined;
}

// Case-insensitive name lookup, used to enforce unique collection names.
// Pass excludeId when renaming so a collection doesn't collide with itself.
export function findCollectionByName(name: string, excludeId?: string): Collection | undefined {
  const row = excludeId
    ? (db
        .prepare('SELECT * FROM collections WHERE LOWER(name) = LOWER(?) AND id != ?')
        .get(name, excludeId) as CollectionRow | undefined)
    : (db.prepare('SELECT * FROM collections WHERE LOWER(name) = LOWER(?)').get(name) as
        | CollectionRow
        | undefined);
  return row ? rowToCollection(row) : undefined;
}

// Renaming counts as an edit — stamps edited_by/edited_at so the card can
// show who last touched the collection and when. edited_by defaults to the
// same placeholder as created_by until a real login system exists.
export function renameCollection(id: string, name: string, editedBy = 'Test User'): Collection | undefined {
  db.prepare('UPDATE collections SET name = ?, edited_by = ?, edited_at = ? WHERE id = ?').run(
    name,
    editedBy,
    Date.now(),
    id
  );
  return getCollection(id);
}

export function insertCollection(c: Collection): void {
  db.prepare(
    `INSERT INTO collections (id, name, type, source, client_type, status, file_name, fields, created_by, created_at, edited_by, edited_at)
     VALUES (@id, @name, @type, @source, @clientType, @status, @fileName, @fields, @createdBy, @createdAt, @editedBy, @editedAt)`
  ).run({
    id: c.id,
    name: c.name,
    type: c.type,
    source: c.source,
    clientType: c.clientType,
    status: c.status,
    fileName: c.fileName,
    fields: JSON.stringify(c.fields),
    createdBy: c.createdBy,
    createdAt: c.createdAt,
    editedBy: c.editedBy,
    editedAt: c.editedAt,
  });
}

export function deleteCollection(id: string): boolean {
  const result = db.prepare('DELETE FROM collections WHERE id = ?').run(id);
  return result.changes > 0;
}

/* ============================= SAVED MAPPINGS ============================= */

interface MappingRowRecord {
  id: string;
  source_id: string;
  target_id: string;
  source_name: string;
  target_name: string;
  rows: string;
  saved_by: string;
  created_at: number;
}

function rowToSavedMapping(row: MappingRowRecord): SavedMapping {
  return {
    id: row.id,
    sourceId: row.source_id,
    targetId: row.target_id,
    sourceName: row.source_name,
    targetName: row.target_name,
    rows: JSON.parse(row.rows),
    savedBy: row.saved_by,
    createdAt: row.created_at,
  };
}

export function listSavedMappings(): SavedMapping[] {
  const rows = db
    .prepare('SELECT * FROM mappings ORDER BY created_at DESC')
    .all() as MappingRowRecord[];
  return rows.map(rowToSavedMapping);
}

export function getSavedMapping(id: string): SavedMapping | undefined {
  const row = db.prepare('SELECT * FROM mappings WHERE id = ?').get(id) as
    | MappingRowRecord
    | undefined;
  return row ? rowToSavedMapping(row) : undefined;
}

export function insertSavedMapping(m: SavedMapping): void {
  db.prepare(
    `INSERT INTO mappings (id, source_id, target_id, source_name, target_name, rows, saved_by, created_at)
     VALUES (@id, @sourceId, @targetId, @sourceName, @targetName, @rows, @savedBy, @createdAt)`
  ).run({
    id: m.id,
    sourceId: m.sourceId,
    targetId: m.targetId,
    sourceName: m.sourceName,
    targetName: m.targetName,
    rows: JSON.stringify(m.rows),
    savedBy: m.savedBy,
    createdAt: m.createdAt,
  });
}

export function deleteSavedMapping(id: string): boolean {
  const result = db.prepare('DELETE FROM mappings WHERE id = ?').run(id);
  return result.changes > 0;
}

/* ============================= CATEGORIES ============================= */

interface CategoryRow {
  id: string;
  name: string;
  created_by: string;
  created_at: number;
}

function rowToCategory(row: CategoryRow): Category {
  return {
    id: row.id,
    name: row.name,
    createdBy: row.created_by || '',
    createdAt: row.created_at,
  };
}

export function listCategories(): Category[] {
  const rows = db.prepare('SELECT * FROM categories ORDER BY name ASC').all() as CategoryRow[];
  return rows.map(rowToCategory);
}

// Case-insensitive — relies on the column's COLLATE NOCASE.
export function findCategoryByName(name: string): Category | undefined {
  const row = db.prepare('SELECT * FROM categories WHERE name = ?').get(name) as CategoryRow | undefined;
  return row ? rowToCategory(row) : undefined;
}

export function insertCategory(c: Category): void {
  db.prepare(
    `INSERT INTO categories (id, name, created_by, created_at) VALUES (@id, @name, @createdBy, @createdAt)`
  ).run({
    id: c.id,
    name: c.name,
    createdBy: c.createdBy,
    createdAt: c.createdAt,
  });
}

/* ============================= SOURCE SYSTEMS ============================= */

interface SourceSystemRow {
  id: string;
  name: string;
  created_by: string;
  created_at: number;
}

function rowToSourceSystem(row: SourceSystemRow): SourceSystem {
  return {
    id: row.id,
    name: row.name,
    createdBy: row.created_by || '',
    createdAt: row.created_at,
  };
}

export function listSourceSystems(): SourceSystem[] {
  const rows = db.prepare('SELECT * FROM source_systems ORDER BY name ASC').all() as SourceSystemRow[];
  return rows.map(rowToSourceSystem);
}

// Case-insensitive — relies on the column's COLLATE NOCASE.
export function findSourceSystemByName(name: string): SourceSystem | undefined {
  const row = db.prepare('SELECT * FROM source_systems WHERE name = ?').get(name) as
    | SourceSystemRow
    | undefined;
  return row ? rowToSourceSystem(row) : undefined;
}

export function insertSourceSystem(s: SourceSystem): void {
  db.prepare(
    `INSERT INTO source_systems (id, name, created_by, created_at) VALUES (@id, @name, @createdBy, @createdAt)`
  ).run({
    id: s.id,
    name: s.name,
    createdBy: s.createdBy,
    createdAt: s.createdAt,
  });
}

/* ============================= ADMIN ============================= */

// Wipes every table clean — collections, saved mappings, categories, and
// source systems. Used by the guarded /api/admin/reset endpoint so someone
// can start completely fresh, e.g. after test data has accumulated.
export function resetAllData(): { collections: number; mappings: number; categories: number; sourceSystems: number } {
  const collections = db.prepare('DELETE FROM collections').run().changes;
  const mappings = db.prepare('DELETE FROM mappings').run().changes;
  const categories = db.prepare('DELETE FROM categories').run().changes;
  const sourceSystems = db.prepare('DELETE FROM source_systems').run().changes;
  return { collections, mappings, categories, sourceSystems };
}
